services:
  nginx:
    image: profsoft-dev/app-nginx:v0.1
    container_name: profsoft-web
    build:
      context: .
      dockerfile: ./build/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app/:/var/www/app/:ro
    networks:
      - app-network

  php:
    image: profsoft-dev/app-php:v0.1
    container_name: profsoft-php
    build:
      context: .
      dockerfile: ./build/php/Dockerfile
#    volumes:
#      - ./app:/var/www/app/:rw
    networks:
      - app-network
      - db-network

  db:
    image: postgres:15.2-alpine3.17
    container_name: profsoft-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=${DB_PGDATA}
    ports:
      - 5432:5432
    volumes:
      - ./postgres:${DB_PGDATA}
    networks:
      - db-network

networks:
  app-network:
    external: false
    name: app-network
  db-network:
    external: false
    name: db-network
