services:
  nginx:
    image: ${IMAGE_APP_WEB}:${APP_NGINX_TAG}
    container_name: profsoft-web
    build:
      context: .
      dockerfile: ./build/nginx/Dockerfile
      args:
        - SERVERNAME_APP=${SERVERNAME_APP}
        - FROM_NGINX_TAG=${FROM_NGINX_TAG}
    ports:
      - "8080:80"
    volumes:
      - ./app/:/var/www/app/:ro
    networks:
      - front-tire

  php:
    image: ${IMAGE_APP_PHP}:${APP_PHP_TAG}
    container_name: profsoft-php
    build:
      context: .
      dockerfile: ./build/php/Dockerfile
      args:
        - FROM_COMPOSER_TAG=${FROM_COMPOSER_TAG}
        - FROM_PHP_TAG=${FROM_PHP_TAG}
#      additional_contexts:
#        appsrc: https://github.com/Keks3377/first-app.git
#    volumes:
#      - ./app:/var/www/app/:rw
    networks:
      - front-tire
      - back-tire

  db:
    image: postgres:${PG_IMAGE_TAG}
    container_name: profsoft-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=${DB_PGDATA}
    volumes:
      - ./postgres:${DB_PGDATA}
    networks:
      - back-tire

networks:
  front-tire:
    external: false
    name: front-tire
  back-tire:
    external: false
    name: back-tire
